logLevel: INFO
denied: '-> You are §cnot approved§r to use §o{1}' # 1 = Item
reload: '-> {1} plugin §areloaded' # 1 = Plugin Name
blacklist:
    TNT: TNT
    FLINT_AND_STEEL: Flint and Steel
    BUCKET: Buckets
    WATER_BUCKET: Water Buckets
    LAVA_BUCKET: Lava Buckets
    FIREBALL: Fire Charges
version: @VERSION@