name: @NAME@
description: Prevent specific items from being used
softdepend: [TimeService]
version: @VERSION@
author: @AUTHOR@
main: @MAIN@
commands:
    'simpleblacklist:reload':
        description: Reload plugin
        permission: simpleblacklist.reload
permissions:
    simpleblacklist.material.all:
        description: Can use all blacklisted materials
        default: op
    simpleblacklist.reload:
        description: Can use reload command
        default: op

