name: SimpleBlacklist
version: @VERSION@
description: Prevent specific items from being used
softdepend: [TimeService]
author: EdGruberman (ed@rjump.com)
main: edgruberman.bukkit.simpleblacklist.Main
commands:
    'simpleblacklist:reload':
        description: Reload plugin
        permission: simpleblacklist.reload
permissions:
    simpleblacklist.override.material:
        description: Can use all blacklisted materials
        default: op
    simpleblacklist.reload:
        description: Can use reload command
        default: op

