blacklist:
    '46':
        message: You are not allowed to place or use TNT.
        allow:
            - [Certified]
    '259':
        message: You are not allowed to use Flint and Steel.
        allow:
            - [Certified]
    '325':
        message: You are not allowed to use Buckets.
        allow:
            - [Certified]
    '326':
        message: You are not allowed to use Water Buckets.
        allow:
            - [Certified]
    '327':
        message: You are not allowed to use Lava buckets.
        allow:
            - [Certified]