denied: 'You have not been approved to use %1$s' # 1 = Item Name
blacklist:
    TNT: TNT
    FLINT_AND_STEEL: Flint and Steel
    BUCKET: Buckets
    WATER_BUCKET: Water Buckets
    LAVA_BUCKET: Lava Buckets
logLevel: RIGHTS
version: @VERSION@