name: SimpleBlacklist
description: Prevent specific items from being used unless authorized.
version: %VERSION%
depend: [MessageManager]
main: edgruberman.bukkit.simpleblacklist.Main
author: EdGruberman (ed@rjump.com)

